priceIsRight/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views as auth_views
from authentication.forms import LoginForm
from stocks import views

urlpatterns = [
     url(r'', include('notetaker.urls')),
     url(r'^admin/', admin.site.urls),
]


#
# urlpatterns = [
#     url(r'notetaker', include('notetaker.urls')),
#     url(r'auth', include('authentication.urls')),
#     url(r'^login/$', auth_views.login, {'template_name': 'login.html', 'authentication_form': LoginForm}, name='login'),
#     url(r'^logout/$', auth_views.logout, {'next_page': '/login'}, name='logout'),
#     url(r'^place_order/$', views.index, name='place_order'),
#     url(r'^order/(?P<id>[0-9]+)/$', views.order_detail, name='order_detail'),
#     url(r'^admin/', admin.site.urls),
#     url(r'^order/(?P<id>[0-9]+)/get_progress/$', views.get_progress, name='get_progress'),
#     url(r'^order/(?P<id>[0-9]+)/get_status/$', views.get_status, name='get_status'),
#     url(r'^order/(?P<id>[0-9]+)/get_children/(?P<child_id>[0-9]+)/$', views.get_children, name='get_children'),
#     url(r'^order/(?P<id>[0-9]+)/get_children/undefined/$', views.get_children_undefined, name='get_children_undefined'),
# ]

stocks/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

stocks/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

from models import ParentOrder

def validate_order_quantity(value):
    if value <= 0:
        raise ValidationError(
            _('Please enter an integer greater than zero.'),
            code='negative'
        )

class ParentOrderForm(forms.ModelForm):

    BUY_OR_SELL_CHOICE = (
        (True, 'Sell'),
    )

    STOCK_CHOICE = (
        ('ACME ETF', 'ACME ETF'),
    )

    is_sell = forms.ChoiceField(label="Buy or Sell?", choices=BUY_OR_SELL_CHOICE, required=True, 
        widget=forms.Select(attrs={'class': 'form-control'}))
    quantity = forms.IntegerField(label='Quantity', required=True,
        error_messages = {'required': _('Enter a whole number.')},
        widget=forms.NumberInput(attrs={'class': 'form-control'}))
    stock_type = forms.ChoiceField(label="Stock Type", choices=STOCK_CHOICE, required=True, 
        widget=forms.Select(attrs={'class': 'form-control'}))

    class Meta:
        model = ParentOrder
        fields = ('is_sell', 'quantity', 'stock_type')

class PauseResumeForm(forms.ModelForm):

    status = forms.CharField(widget = forms.HiddenInput(), required = True)

    class Meta:
        model = ParentOrder
        fields = ('status',)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
	    <meta name="description" content="">
	    <meta name="author" content="">
	    <link rel="icon" href="{% static "seekybrand.png" %}">

	    <title>NoteTaker</title>

		<!--BOOTSTRAPS jquery-->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>

	    <!-- Bootstrap core JS -->
	    <link href="{% static "bootstrap/js/bootstrap.min.js" %}" rel="stylesheet">

	    <!-- Bootstrap core CSS -->
	    <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

		<!-- Custom CSS -->
    	<link href="{% static "bootstrap/css/simple-sidebar.css" %}" rel="stylesheet">

	    <!-- Override .navbar-brand style -->
	    <style>
	    	.navbar-inverse .navbar-brand:hover,
			.navbar-inverse .navbar-brand:focus {
  			background-color: transparent;
  			color: #999999;
		}
	    </style>


		<!-- include libs stylesheets -->
		<!-- include libraries BS3 -->
		<link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.1/css/bootstrap.min.css" />
		<script type="text/javascript" src="//netdna.bootstrapcdn.com/bootstrap/3.0.1/js/bootstrap.min.js"></script>


	    {% block head-extras %}
	    {% endblock %}

	    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	    <!--[if lt IE 9]>

	    <![endif]-->


	</head>
	<body>

	    <div id="wrapper">

        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                </li>
				<li>
                    <a href="/">
						{% if user.is_authenticated %}
                        Welcome {{ user.get_full_name|default:user }}
						{% endif %}
                    </a>
                </li>
				<li class="sidebar-brand">
					<img src="{% static "seekybrand.png" %}" style="width: 50%;">
				</li>
				<li class="sidebar-brand">

                </li>
                <li>
                    <a href="/notebooks">
						<i style="font-size:1em;" class="glyphicon glyphicon-book"></i>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Notebooks
					</a>
                </li>
                <li>
                    <a href="/documents"><i style="font-size:1em;" class="glyphicon glyphicon-file"></i>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Documents
					</a>
                </li>
                <li>
                    <a href="/tags"><i style="font-size:1em;" class="glyphicon glyphicon-tags"></i>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Tags
					</a>
                </li>
                <li>
                    <a href="/noteedit"><i style="font-size:1em;" class="glyphicon glyphicon-edit"></i>
						&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Notes
					</a>
                </li>
                <li>
                    <a href="/friends">Friends</a>
                </li>
                <li>
                    <a href="/summernote">Summer</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>

        <!-- /#sidebar-wrapper -->



		<nav class="navbar navbar-inverse navbar-fixed-top">
	      <div class="container-fluid">
	      	 <div class="navbar-header">
	      	  <!-- this section will make navbar responsive especially on small screens -->
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		       <a href="#menu-toggle" class="navbar-brand" id="menu-toggle">{% if user.is_authenticated %}Seeky Notes{% endif %}</a>
		    </div>

		    <!-- this section will make the actual navbar -->
	        <div id="navbar" class="navbar-collapse collapse">
	          {% if user.is_authenticated %}
	          <ul class="nav navbar-nav navbar-right">
	            <li><a href="/notebooks">Home</a></li>
	            <li><a href="{% url 'logout' %}">Logout</a></li>
	          </ul>
	          {% endif %}

	        </div>
	      </div>
	    </nav>

	    <div class="container-fluid">
      	  <div class="row">
            <div class="col-sm-8 col-sm-offset-2 col-md-10 col-md-offset-1 main">

			{% block content %}
			{% endblock %}

			</div>
      	  </div>
     	</div>

		<!--- end wrapper -->
		</div>

	    <!-- Bootstrap core JavaScript ================================================== -->
	    <!-- Placed at the end of the document so the pages load faster -->

		<!--BOOTSTRAPS jquery-->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.0.0/jquery.min.js"></script>

		<script>
			{% if user.is_authenticated %}
				$("#wrapper").toggleClass("toggled");
			{% endif %}
		</script>

		<script>
    	$("#menu-toggle").click(function(e) {
     		e.preventDefault();
      		$("#wrapper").toggleClass("toggled");
    	});
    	</script>

	</body>
</html>

templates/documents.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block head-extras %}

    <!--FB sdk-->


<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '272396783170710', // Set YOUR APP ID
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });

    FB.Event.subscribe('auth.authResponseChange', function(response)
    {
     if (response.status === 'connected')
    {
        document.getElementById("message").innerHTML +=  "<br>Connected to Facebook";
        //SUCCESS

    }
    else if (response.status === 'not_authorized')
    {
        document.getElementById("message").innerHTML +=  "<br>Failed to Connect";

        //FAILED
    } else
    {
        document.getElementById("message").innerHTML +=  "<br>Logged Out";

        //UNKNOWN ERROR
    }
    });

    };

    function Login()
    {

        FB.login(function(response) {
           if (response.authResponse)
           {
                getUserInfo();
            } else
            {
             console.log('User cancelled login or did not fully authorize.');
            }
         },{scope: 'email,user_photos,user_videos'});

    }

  function getUserInfo() {
        FB.api('/me', function(response) {

      var str="<b>Name</b> : "+response.name+"<br>";
          str +="<b>Link: </b>"+response.link+"<br>";
          str +="<b>Username:</b> "+response.username+"<br>";
          str +="<b>id: </b>"+response.id+"<br>";
          str +="<b>Email:</b> "+response.email+"<br>";
          str +="<input type='button' value='Get Photo' onclick='getPhoto();'/>";
          str +="<input type='button' value='Logout' onclick='Logout();'/>";
          document.getElementById("status").innerHTML=str;

    });
    }
    function getPhoto()
    {
      FB.api('/me/picture?type=normal', function(response) {

          var str="<br/><b>Pic</b> : <img src='"+response.data.url+"'/>";
          document.getElementById("status").innerHTML+=str;

    });

    }
    function Logout()
    {
        FB.logout(function(){document.location.reload();});
    }

  // Load the SDK asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));

</script>

{% endblock %}

{% block content %}



    <h2>Secret header</h2>
    <h1>DOCUMENTS</h1>
    {% if all_documents %}

        {% for document, owner in all_documents.items %}
            <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
                <div class="panel panel-primary">
                    <a href="/documents/{{ document.id }}/">
                        <div class="panel-heading">
                            <div class="row">
                                <div class="col-xs-2">
                                    <i style="font-size:2.8em;" class="glyphicon glyphicon-file"></i>
                                </div>
                                <div class="col-xs-10 text-right">
                                    <div>{{ document.title }}</div>
                                </div>
                            </div>
                        </div>
                    </a>


                    <div class="panel-footer">

                        <!--footer element to link to author-->
                        <a href="/profile/{{ owner.id }}/">
                            <span class="pull-left">Authored by {{owner.get_full_name|default:owner}}</span>
                        </a>

                        <!--footer element to delete document-->
                        <a data-toggle="collapse" href="#docdel{{document.id}}">
                            <span class="pull-right"><i style="font-size:1.5em;" class="glyphicon glyphicon-trash"></i></span>
                        </a>

                        <!--footer element to share document-->
                        <a data-toggle="collapse" href="#ppladd{{document.id}}">
                            <span class="pull-right"><i style="font-size:1.5em;" class="glyphicon glyphicon-share"></i></span>
                        </a>

                        <div class="clearfix"></div>
                    </div>


                    <!--form for adding permissions-->


                    <div class="collapse" id="ppladd{{document.id}}">
                        <div class="panel-footer">

                                        <form class="card" method="POST">
                                            <div class="card-content">
                                                <div class="row">
                                                    {%csrf_token%}
                                                    <input type="hidden" name="post_type" value="ppl">
                                                    <input type="hidden" name="docid" value="{{ document.id }}">


                                                    <!--person to authorize-->
                                                    <label for="person" style="color:#337ab7;">&nbsp;&nbsp;&nbsp;&nbsp;Authorize </label>
                                                    <select class="selectpicker" id="person" name="person" title="choose a person">
                                                        {% for ppl in all_users %}
                                                            <option value="{{ ppl.id }}">{{ ppl.get_full_name|default:ppl.username }}</option>
                                                        {% endfor %}
                                                    </select>

                                                    <!--authorization type-->
                                                    <label for="authtype" style="color:#337ab7;"> to </label>
                                                    <select class="selectpicker" id="authtype" name="authtype" title="choose a authtype">
                                                            <option value="0">Read</option>
                                                            <option value="1">Write</option>
                                                            <option value="2">Comment</option>
                                                    </select>


                                                </div>
                                                <div class="row">
                                                    &nbsp;&nbsp;&nbsp;
                                                    <button type="submit" class="btn btn-primary">Submit</button>

                                                </div>
                                            </div>
                                        </form>

                        </div>
                    </div>

                    <!--end toggle stuff-->

                    <!--toggle delete-->
                    <div class="collapse" id="docdel{{document.id}}">
                        <div class="panel-footer">

                                        <form class="card" method="POST">
                                            <div class="card-content">
                                                <div class="row">
                                                    {%csrf_token%}
                                                    <input type="hidden" name="post_type" value="del">
                                                    <input type="hidden" name="docid" value="{{ document.id }}">


                                                    <!--Delete Text-->
                                                    <label for="person" style="color:#337ab7;">&nbsp;&nbsp;&nbsp;&nbsp;Delete {{ document.title}}? </label>

                                                </div>
                                                <div class="row">
                                                    &nbsp;&nbsp;&nbsp;
                                                    <button type="submit" class="btn btn-success">YES</button>
                                                    <button class="btn btn-danger" data-toggle="collapse" href="#docdel{{document.id}}">
                                                        NO
                                                    </button>

                                                </div>
                                            </div>
                                        </form>

                        </div>
                    </div>

                    <!--end toggle stuff-->


                </div>
            </div>

        {% endfor %}



    {% endif %}

    <!--code for creating new document-->

    <div class="col-lg-4 col-md-6 col-sm-12 col-xs-12">
        <div class="panel panel-primary" >
            <a data-toggle="collapse" href="#collapseExample">
                <div class="panel-heading">

                    <div class="row">
                        <div class="col-xs-2">
                            <i style="font-size:2.8em; color:#337ab7;" class="glyphicon glyphicon-plus"></i>
                        </div>
                        <div class="col-xs-10 text-right">
                            <p style="color:#337ab7;">Create New Document</p>
                        </div>
                    </div>

                </div>
            </a>

            <!--stuff the gets toggled-->
            <div class="collapse" id="collapseExample">
                <div class="panel-footer">

                    <form class="card" method="POST">
                        <div class="card-content">
                            <div class="row">
                                {%csrf_token%}
                                <input type="hidden" name="post_type" value="create">
                                <label for="title" style="color:#337ab7;">&nbsp;&nbsp;&nbsp;&nbsp;Title: </label>
                                <input id="title" type="text" name="title" style="background-color:white;color:#337ab7;">
                            </div>

                            {% if all_notebooks%}
                            <div class="row">
                                <div class="col-xs-8 col-lg-2">
                                    <label for="title" style="color:#337ab7;">Notebook: </label>
                                    <select class="selectpicker" id="selectnotebook" name="selectnotebook" title="choose a notebook">
                                        {% for nb in all_notebooks %}
                                            <option value="{{ nb.id }}">{{ nb }}</option>
                                        {% endfor %}
                                    </select>
                                </div>
                            </div>
                            {% endif %}

                            <div class="row">
                                &nbsp;&nbsp;&nbsp;
                                <button type="submit" class="btn btn-primary">Submit</button>
                            </div>
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>

{% endblock %}

templates/friends.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block head-extras %}

{% endblock %}

{% block content %}
<h2>Hidden</h2>
Welcome {{ social_user }}
of UID {{ social_user.uid }}
with access token {{ social_user.access_token }}



<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '272396783170710',
      xfbml      : true,
      version    : 'v2.9'
    });

    <!--FB.ui(-->
     <!--{-->
      <!--method: 'share',-->
      <!--href: 'https://developers.facebook.com/docs/'-->
    <!--}, function(response){});-->

    FB.api('/{{ social_user.uid }}/picture?type=normal', function(response) {

          var str="<br/><b>Pic</b> : <img src='"+response.data.url+"'/>";
          document.getElementById("profilepic").innerHTML+=str;
          document.getElementById("profilepic").innerHTML+="<br>hello";

    });

    FB.api('/{{ social_user.uid }}/friends' , function(response) {
        document.getElementById("profilepic").innerHTML+="<br>FRIENDS";
        var num_friends = response.summary;
        document.getElementById("profilepic").innerHTML+=num_friends;
        for (var i = 0; i < num_friends; i++) {
            document.getElementById("profilepic").innerHTML+="<br>GOt FRIEND";

        }
        for (var name in response.data) {

            document.getElementById("profilepic").innerHTML+="<br>GOt FRIEND";

        }

    });

    FB.getLoginStatus(function(response) {
    document.getElementById("profilepic").innerHTML +=  "<br>hi3";
      if (response.status === 'connected') {
        document.getElementById("profilepic").innerHTML +=  "<br>Logged In";
      }
      else {
        FB.login();
        document.getElementById("profilepic").innerHTML +=  "<br>Logged Out";
      }
    });
    document.getElementById("profilepic").innerHTML +=  "<br>Log";

    FB.AppEvents.logPageView();
  };

  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/en_US/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));


</script>

<h1>HI</h1>
<div id="profilepic"></div>

<script>
    var HttpClient = function() {
        this.get = function(aUrl, aCallback) {
            var anHttpRequest = new XMLHttpRequest();
            anHttpRequest.onreadystatechange = function() {
                if (anHttpRequest.readyState == 4 && anHttpRequest.status == 200)
                    aCallback(anHttpRequest.responseText);
            }

            anHttpRequest.open( "GET", aUrl, true );
            anHttpRequest.send( null );
        }
    }
    var client = new HttpClient();
    client.get('GET /v2.5/me HTTP/1.1
Host: graph.facebook.com', function(response) {
        // do something with response
    });
</script>
{% endblock %}

templates/index.html
<!DOCTYPE html>
<html>
<head>
<title>Facebook Login JavaScript Example</title>
<meta charset="UTF-8">
</head>
<body>
<script>
  // This is called with the results from from FB.getLoginStatus().
  function statusChangeCallback(response) {
    console.log('statusChangeCallback');
    console.log(response);
    // The response object is returned with a status field that lets the
    // app know the current login status of the person.
    // Full docs on the response object can be found in the documentation
    // for FB.getLoginStatus().
    if (response.status === 'connected') {
      // Logged into your app and Facebook.
      testAPI();
    } else {
      // The person is not logged into your app or we are unable to tell.
      document.getElementById('status').innerHTML = 'Please log ' +
        'into this app.';
    }
  }

  // This function is called when someone finishes with the Login
  // Button.  See the onlogin handler attached to it in the sample
  // code below.
  function checkLoginState() {
    FB.getLoginStatus(function(response) {
      statusChangeCallback(response);
    });
  }

  window.fbAsyncInit = function() {
  FB.init({
    appId      : '272396783170710',
    cookie     : true,  // enable cookies to allow the server to access
                        // the session
    xfbml      : true,  // parse social plugins on this page
    version    : 'v2.8' // use graph api version 2.8
  });

  // Now that we've initialized the JavaScript SDK, we call
  // FB.getLoginStatus().  This function gets the state of the
  // person visiting this page and can return one of three states to
  // the callback you provide.  They can be:
  //
  // 1. Logged into your app ('connected')
  // 2. Logged into Facebook, but not your app ('not_authorized')
  // 3. Not logged into Facebook and can't tell if they are logged into
  //    your app or not.
  //
  // These three cases are handled in the callback function.

  FB.getLoginStatus(function(response) {
    statusChangeCallback(response);
  });

  };

  // Load the SDK asynchronously
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/sdk.js";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

  // Here we run a very simple test of the Graph API after login is
  // successful.  See statusChangeCallback() for when this call is made.
  function testAPI() {
    console.log('Welcome!  Fetching your information.... ');
    FB.api('/me', function(response) {
      console.log('Successful login for: ' + response.name);
      document.getElementById('status').innerHTML =
        'Thanks for logging in, ' + response.name + '!';
    });
  }
</script>

<!--
  Below we include the Login Button social plugin. This button uses
  the JavaScript SDK to present a graphical Login button that triggers
  the FB.login() function when clicked.
-->
<h1>HI</h1>
<fb:login-button scope="public_profile,email" onlogin="checkLoginState();">
</fb:login-button>

<div id="status">
</div>

</body>
</html>

templates/order_detail.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block head-extras %}
    <!-- Custom styles for this page -->
    <link href="{% static "stocks/dashboard.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div>
<h2 class="sub-header">Order: {{ parent_order.quantity }} x {{ parent_order.stock_type }} 
{% if parent_order.status != 'C' and parent_order.status != 'X' %} 
  <div class="btn-toolbar inline" id="order-buttons" role="toolbar">
    {% if parent_order.status == 'S' %} 
      <form id="resume" action="{% url 'order_detail' parent_order.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="status" value="P">
      </form>
      <button class="btn btn-success" type="submit" form="resume">Resume</button>
    {% endif %}
    {% if parent_order.status == 'P' %} 
      <form id="pause" action="{% url 'order_detail' parent_order.id %}" method="post">
        {% csrf_token %}
        <input type="hidden" name="status" value="S">
      </form>
      <button class="btn btn-info" type="submit" form="pause">Pause</button>
    {% endif %}
    <form id="cancel" action="{% url 'order_detail' parent_order.id %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="status" value="X">
    </form>
    <button class="btn btn-danger" type="submit" form="cancel">Cancel</button>
  </div>
{% endif %} 
</h2>
  
<p id="stats"> <b>Average Price:</b> {{ average_price }}, <b>Gross Sale Price:</b> {{ total_price }}, <b>Total Quantity Sold:</b> {{ total_sold }} </p>
</div>

<div class="progress">

  <div id="progress-{{parent_order.id}}" data-id="{{order.id}}" class="progress-bar 
      {% if parent_order.status == 'P' %} 
          progress-bar-success progress-bar-striped active
      {% endif %}
      {% if parent_order.status == 'C' %} 
          progress-bar-success progress-bar
      {% endif %}
      {% if parent_order.status == 'F' %} 
          progress-bar-danger progress-bar-striped active
      {% endif %}" role="progressbar"
    aria-valuenow="{{progress}}" aria-valuemin="0" aria-valuemax="100" style="min-width:4em; width:{{progress}}%">
    {{progress}}%

  </div>
</div>

<div class="table-responsive">
    <table class="table table-striped" id="children-{{parent_order.id}}">
      <thead>
        <tr>
          <th>Time</th>
          <th>Child Order Number</th>
          <th>Quantity</th>
          <th>Status</th>
          <th>Attempted Price (USD)</th>
        </tr>
      </thead>
        {% if child_orders %}
        <tbody>
            {% for co in child_orders %}
                {% if co.is_successful %} 
                    <tr class="success">
                {% else %}
                    <tr class="danger">
                {% endif %}
                    <td> {{ co.time_executed }} EST
                    <td class="child-id"> {{ co.id }}
                    <td> {{ co.quantity }}
                    <td> {% if co.is_successful %} 
                            SUCCEEDED
                        {% else %}
                            FAILED
                        {% endif %}
                    <td> {{ co.price }}
              </tr>
          {% endfor %}
      </tbody>
      {% endif %}
  </table>
</div>

<script> 
var parent_order_id = [{{ parent_order.id }}];
var progress_type = "detail";
</script>
<script src="{% static "js/progress.js" %}" language="javascript" type="text/javascript"></script>


{% endblock %}

templates/place_order.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block head-extras %}
    <!-- Custom styles for this page -->
    <link href="{% static "stocks/dashboard.css" %}" rel="stylesheet">
{% endblock %}

{% block content %}

<div class="col-sm-8 col-sm-offset-2 col-md-10 col-md-offset-1 main">

  <h2 class="sub-header">Craigslist For Stocks</h2>

  <form action="{% url 'place_order' %}" method="post">

  	{% csrf_token %}

  	<p>{{ form.quantity.label_tag }} {{ form.quantity }}</p>
      {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
      {% endif %}
    <p>{{ form.is_sell.label_tag }} {{ form.is_sell }} </p>
    <p><label for="id_stock_type">ETF Ticker </label>{{ form.stock_type }} </p>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
      Submit Order
    </button>

    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Order Confimation</h4>
          </div>
          <div class="modal-body">
            Make this order?
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <button class="btn btn-default btn-success" type="submit" value="Submit" onclick="location.href="{% url 'place_order' %}" ">Submit</button>
          </div>
        </div>
      </div>
    </div>

  </form>

</div>


{% endblock %}

templates/register.html
{% extends 'base.html' %}

{% block content %}

<h1>Register with The_Price_is_Right</h1>

{% if registered %}
<strong>Thank you for registering!</strong>
{% else %}

<form id="user_form" method="post" action=""
        enctype="multipart/form-data">

    {% csrf_token %}

    <!-- Display each form. The as_p method wraps each element in a paragraph
         (<p>) element. This ensures each element appears on a new line,
         making everything look neater. -->
    {{ user_form.as_p }}

    <!-- Provide a button to click to submit the form. -->
    <input type="submit" name="submit" value="Register" />
</form>
{% endif %}

{% endblock %}